//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsurance_WebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_insuranceEntities : DbContext
    {
        public db_insuranceEntities()
            : base("name=db_insuranceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<insuree_main> insuree_main { get; set; }
        public virtual DbSet<car_main> car_main { get; set; }
        public virtual DbSet<insuree_hist> insuree_hist { get; set; }
        public virtual DbSet<insuree_info> insuree_info { get; set; }
        public virtual DbSet<insuree_quote> insuree_quote { get; set; }
        public virtual DbSet<vinsuree_data_all> vinsuree_data_all { get; set; }
    }
}
