//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsurance_WebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_insuranceEntities : DbContext
    {
        public db_insuranceEntities()
            : base("name=db_insuranceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<car_main> car_main { get; set; }
        public virtual DbSet<insuree_hist> insuree_hist { get; set; }
        public virtual DbSet<insuree_info> insuree_info { get; set; }
        public virtual DbSet<insuree_main> insuree_main { get; set; }
        public virtual DbSet<insuree_quote> insuree_quote { get; set; }
        public virtual DbSet<login_main> login_main { get; set; }
        public virtual DbSet<vinsuree_data_all> vinsuree_data_all { get; set; }
        public virtual DbSet<vlogin_user_all> vlogin_user_all { get; set; }
    
        public virtual ObjectResult<spGetInsureeKey_Result> spGetInsureeKey(ObjectParameter insuree_key)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetInsureeKey_Result>("spGetInsureeKey", insuree_key);
        }
    }
}
