//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsurance_WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class insuree_main
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public insuree_main()
        {
            this.car_main = new HashSet<car_main>();
            this.insuree_hist = new HashSet<insuree_hist>();
            this.insuree_info = new HashSet<insuree_info>();
            this.insuree_quote = new HashSet<insuree_quote>();
        }
    
        public int insuree_key { get; set; }
        public int login_user_key { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.DateTime> upd_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<car_main> car_main { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insuree_hist> insuree_hist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insuree_info> insuree_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insuree_quote> insuree_quote { get; set; }
        public virtual login_main login_main { get; set; }
    }
}
