//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsurance_WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class insuree_info
    {
        public int info_key { get; set; }
        public int insuree_key { get; set; }
        public string email { get; set; }
        public System.DateTime dob { get; set; }
        public string state { get; set; }
        public int zip { get; set; }
    
        public virtual insuree_main insuree_main { get; set; }
    }
}
