//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsurance_WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vinsuree_data_all
    {
        public int insuree_key { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string state { get; set; }
        public Nullable<int> zip { get; set; }
        public Nullable<int> car_year { get; set; }
        public string car_make { get; set; }
        public string car_model { get; set; }
        public string coverage_type { get; set; }
        public string dui { get; set; }
        public string tickets { get; set; }
        public string curr_quote { get; set; }
        public string prev_quote { get; set; }
    }
}
